# Research configuration
# config/research_config.yaml
sources:
  academic:
    - name: "Google Scholar"
      base_url: "https://scholar.google.com"
      priority: 1
    - name: "Transport Research Board"
      base_url: "https://trb.org"
      priority: 2
  
  industry:
    - name: "Transport Reports"
      base_url: "https://www.transport-reports.com"
      priority: 1
    - name: "Industry Database"
      base_url: "https://www.transport-industry-db.com"
      priority: 2

  news:
    - name: "Transport News"
      base_url: "https://www.transport-news.com"
      priority: 1
    - name: "Regional Updates"
      base_url: "https://www.regional-transport.com"
      priority: 2

update_frequency:
  scraping: "daily"
  research: "weekly"
  reports: "monthly"

validation:
  min_sources: 3
  confidence_threshold: 0.8
  required_fields:
    - title
    - source
    - date
    - content